### ISSUE TITLE
No way to edit About

### ISSUE THREAD

**Issue by Cryptwright** [raviriley/agency-jekyll-theme#36]
The about section just says a title, and then puts the text down twice, once as a subheader and once as the body.  I do not see a way to actually create a body of text.

**Comment by rbenitezpagan** [comment]
@Cryptwright  I submitted PR #37 can you try it out? You can do it by changing the remote theme to rbenitezpagan/agency-jekyll-theme until it gets approved here.

**Comment by Cryptwright** [comment]
This may fix the other issue, but does not address the fact that the about page does not have a spot in the config.yml to add a body of text.  it only shows the subheader twice.

**Comment by rbenitezpagan** [comment]
@Cryptwright you should be able to add text to that section using this variable: https://github.com/raviriley/agency-jekyll-theme-starter/blob/64a4039c8e9fa16b0e1922fb6f933858d67dceaf/_data/sitetext.yml#L73

Please use my remote theme for testing `rbenitezpagan/agency-jekyll-theme`

Variable text is not a sub-header to the best of my knowledge.

**Comment by Cryptwright** [comment]
Please see my revised initial comment.  That TEXT variable shows up as a subheader AND as the body, in both places.  This makes it unusable as the body.

**Comment by rbenitezpagan** [comment]
@Cryptwright I fixed it in my repo. Can you try it out? Use my remote theme `rbenitezpagan/agency-jekyll-theme` I added variable `body`.

![image](https://user-images.githubusercontent.com/11214492/128943039-9edb9e01-61e1-4125-8538-4a3d44d938bd.png)

**Comment by Cryptwright** [comment]
Does not work yet.  I do not see the rendering code in the commit.  I see the sitetext file is added to the commit but not whichever file actually renders the page.

**Comment by rbenitezpagan** [comment]
I fixed the theme but you have to also download the fixed theme-starter or manually add the changes to your project.

These are the 2 changed files (you can ignore the Gemfile) https://github.com/raviriley/agency-jekyll-theme-starter/pull/5/files

**Comment by Cryptwright** [comment]
i see how it should work based on the commits but still can't get it to work by changing my remote theme.  i'll keep working on it.  thanks!

**Comment by rbenitezpagan** [comment]
@Cryptwright if you want to make a public version so I can help or add me to your repo temporarily. Let me know.

**Comment by Cryptwright** [comment]
I got it! I forgot to unset my custom layout to undo my workaround.  Works good now.
